changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bugs
      labels:
        - bug
    - title: Improvements
      labels:
        - improvement
        - enhancement
    - title: Other Changes
      labels:
        - "*"